config/routes.rb
Rails.application.routes.draw do
  resources :foods do
    collection do
      get 'location/:loc' => "foods#index"
      get 'qr_codes' => "foods#qr_codes", :as => :all_qr_codes
    end
  end

  root 'foods#index'

end

app/models/food.rb
class Food < ActiveRecord::Base

  LOCATIONS = {"1" => "Kühlschrank", "2" => "Gefrierfach - Oben", "3" => "Gefrierfach - Mitte", "4" => "Gefrierfach - Unten"}

  def location_name
    if location.present?
      Food::LOCATIONS[location]
    else
      "- unbenutzt -"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :get_base_qr_url, only: [:show, :edit, :update, :destroy, :index, :qr_index]
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: 'freezer', password: 'freezer', only: [:create,:destroy]

  # GET /foods
  # GET /foods.json
  def index
    if params[:loc]
      @foods = Food.where(:location => params[:loc])
      @location_name = Food::LOCATIONS[params[:loc]]
    else
      @foods = Food.all
    end
    @all_qr_code = RQRCode::QRCode.new( "#{@url_for_qr_code_base}", :size => 6, :level => :h )
    @locations = {}
    Food::LOCATIONS.each do |key,value|
      @locations[key] = RQRCode::QRCode.new( "#{@url_for_qr_code_base}/location/#{key}", :size => 6, :level => :h )
    end
  end

  def qr_codes
    @foods = Food.all
    @all_qr_code = RQRCode::QRCode.new( "#{@url_for_qr_code_base}", :size => 6, :level => :h )
    @locations = {}
    Food::LOCATIONS.each do |key,value|
      @locations[key] = RQRCode::QRCode.new( "#{@url_for_qr_code_base}/location/#{key}", :size => 6, :level => :h )
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
      url_for_qr_code = "#{@url_for_qr_code_base}/#{@food.id}"
      @edit_qr_code = RQRCode::QRCode.new( "#{url_for_qr_code}/edit", :size => 6, :level => :h )
    end

    def get_base_qr_url
      host_port = "" 
      host_port = ":3000" if request.port.to_i != 80
      @url_for_qr_code_base = "#{request.protocol}#{request.host}#{host_port}/foods"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:title, :embedded_at, :product_code, :best_before, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for @food, :html => { :class => "form-horizontal food" } do |f| %>

  <% if @food.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @food.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :embedded_at, "Eingelagert am", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :embedded_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:embedded_at) %>
  </div>
  <!-- <div class="form-group">
    <%#= f.label :product_code, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%#= f.text_field :product_code, :class => 'form-control' %>
    </div>
    <%#=f.error_span(:product_code) %>
  </div> -->
  <div class="form-group">
    <%= f.label :best_before, "Mindestens haltbar bis", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :best_before, :class => 'form-control' %>
    </div>
    <%=f.error_span(:best_before) %>
  </div>
  <div class="form-group">
    <%= f.label :location, "Ort", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :location, options_for_select(Food::LOCATIONS.map{|key,value| [value,key.to_s]}, @food.try(:location)), :class => 'form-control', :include_blank => "- unbenutzt -" %>
    </div>
    <%=f.error_span(:location) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                foods_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<% content_for :sidebar do %>
  <% if @edit_qr_code.present? %>
    <h3>QR Code</h3>
    <%= render partial: "qr_code", object: @edit_qr_code %>
  <% end %>
<% end %>

app/views/foods/_qr_code.html.erb
<% if qr_code.present? %>
  <table id="qr_code">
    <% qr_code.modules.each_index do |x| %>
      <tr>  
      <% qr_code.modules.each_index do |y| %>
       <% if qr_code.dark?(x,y) %>
        <td class="black"/>
       <% else %>
        <td class="white"/>
       <% end %>
      <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/foods/edit.html.erb
<%- model_class = Food -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/foods/index.html.erb
<%- model_class = Food -%>
<div class="page-header">
  <% if @location_name.present? %>
    <h1><%= @location_name %>:</h1>
  <% else %>
    <h1>Übersicht:</h1>
  <% end %>
</div>
<div class="table-responsive hidden-xs">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Ort</th>
        <th>MHD</th>
        <th>Eingelagert am</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= link_to(food.title, edit_food_path(food), :class => "btn btn-default") %></td>
          <td><%= food.location_name %></td>
          <td><%=l(food.best_before) if food.best_before.present? %></td>
          <td><%=l(food.embedded_at) if food.embedded_at.present? %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_food_path(food), :class => 'btn btn-default btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="visible-xs">
  <div class="list-group ">
    <div class="list-group-item row active">
      <div class="col-xs-4">Name</div>
      <div class="col-xs-4">Ort</div>
      <div class="col-xs-4">MHD</div>
    </div>
    <% @foods.each do |food| %>
        <%= link_to(edit_food_path(food), :class => "list-group-item row") do %>
          <div class="col-xs-4"><%= food.title %></div>
          <div class="col-xs-4"><%= food.location_name %></div>
          <div class="col-xs-4"><%= food.best_before %></div>
        <% end %>
      
    <% end %>
  </div>

</div>

<div class="panel panel-default hidden-xs">
  <div class="panel-body">
    <h3>Was ist in einem Ort:</h3>
    <div class="row">
    <% if @locations.any? %>
      <% @locations.each do |loc,qrcode| %>
      <div class="col-md-5">
        <div class="thumbnail ">
          <h3><%= link_to Food::LOCATIONS[loc], foods_path(:loc => loc), :class => "btn btn-default" %></h3>
          <%= render partial: "qr_code", object: qrcode %>
        </div>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>


<% content_for :sidebar do %>
  <div class="hidden-xs">
    <% if @all_qr_code.present? %>
      <h3><%= link_to("Übersicht", "/", :class => "btn btn-default") %></h3>
      <%= render partial: "qr_code", object: @all_qr_code %>
    <% end %>
  </div>
  <div class="visible-xs panel-body">
    <%= link_to("Übersicht", "/", :class => "btn btn-default col-xs-12") %><br>
    <% if @locations.any? %>
      <% @locations.each do |loc,qrcode| %>
        <%= link_to Food::LOCATIONS[loc], foods_path(:loc => loc), :class => "btn btn-default col-xs-12" %>
      <% end %>
    <% end %>
</div>
<% end %>

app/views/foods/new.html.erb
<%- model_class = Food -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/foods/qr_codes.html.erb
<%= render partial: "qr_code", object: @all_qr_code %>

<hr>

<% @locations.each do |loc,qrcode| %>
  <%= render partial: "qr_code", object: qrcode %>
  <br>
<% end %>

<hr>

<% @foods.each do |food| %>
  <% url_for_qr_code = "#{@url_for_qr_code_base}/#{food.id}"  %>
  <% edit_qr_code = RQRCode::QRCode.new( "#{url_for_qr_code}/edit", :size => 6, :level => :h ) %>
  <%= render partial: "qr_code", object: edit_qr_code %>
  <br>
<% end %>

app/views/foods/show.html.erb
<%- model_class = Food -%>
<div class="page-header">
  <h1><%= @food.title %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Eingelagert am:</strong></dt>
  <dd><%= l(@food.embedded_at) if @food.embedded_at.present? %></dd>
  <dt><strong>Mindestens haltbar bis:</strong></dt>
  <dd><%= l(@food.best_before) if @food.best_before.present? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_code) %>:</strong></dt>
  <dd><%= @food.product_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @food.location_name %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              foods_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_food_path(@food), :class => 'btn btn-default' %>


<% content_for :sidebar do %>
  <h3>QR Code</h3>
  <%= render partial: "qr_code", object: @edit_qr_code %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Freezer" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Freezer</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Lebensmittel", "/foods"  %></li>
            <li><%= link_to "Neue Tupperware anlegen", new_food_path() %></li>
            <li><%= link_to "Alle QR-Codes", all_qr_codes_foods_path() %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-4">
          <div class="well sidebar-nav">
            <%= yield :sidebar %>
            <!-- <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul> -->
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>